import Rating from '@mui/material/Rating';


const productsData = [
    {
        id: 1,
        image: "./assets/images/jbl-blue.png",
        name: "JBL T450",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "5.0",
        stars: <Rating name="read-only" value={5} readOnly />,
        reviews: 274,
        price:  298,
    },
    {
        id: 2,
        image: "./assets/images/jbl-blue.png",
        name: "JBL T450",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: '4.0',
        stars: <Rating name="read-only" value={4} readOnly />,
        reviews: 274,
        price:  298,
    },
    {
        id: 3,
        image: "./assets/images/jbl-blue.png",
        name: "JBL T450",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "4.0",
        stars: <Rating name="read-only" value={4} readOnly />,
        reviews: 274,
        price:  298,
    },
    {
        id: 4,
        image: "./assets/images/jbl-blue.png",
        name: "JBL T450",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "5.0",
        stars: <Rating name="read-only" value={5} readOnly />,
        reviews: 274,
        price:  298,
    },
    {
        id: 5,
        image: "./assets/images/jbl-blue.png",
        name: "JBL T450",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "3.0",
        stars: <Rating name="read-only" value={3} readOnly />,
        reviews: 274,
        price:  298,
    },
    {
        id: 6,
        image: "./assets/images/jbl-blue.png",
        name: "JBL T450",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "5.0",
        stars: <Rating name="read-only" value={5} readOnly />,
        reviews: 274,
        price:  298,
    },
    {
        id: 7,
        image: "./assets/images/jbl-blue.png",
        name: "JBL T450",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "5.0",
        stars: <Rating name="read-only" value={5} readOnly />,
        reviews: 274,
        price:  298,
    },
    {
        id: 8,
        image: "./assets/images/jbl-blue.png",
        name: "JBL T450",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "4.0",
        stars: <Rating name="read-only" value={4} readOnly />,
        reviews: 274,
        price:  298,
    },
    {
        id: 9,
        image: "./assets/images/jbl-blue.png",
        name: "JBL T450",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "5.0",
        stars: <Rating name="read-only" value={5} readOnly />,
        reviews: 274,
        price:  298,
    },
    {
        id: 10,
        image: "./assets/images/jbl-blue.png",
        name: "JBL T450",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "3.5",
        stars: <Rating name="read-only" value={3} readOnly />,
        reviews: 274,
        price:  298,
    },
    {
        id: 11,
        image: "./assets/images/jbl-blue.png",
        name: "JBL T450",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "5.0",
        stars: <Rating name="read-only" value={5} readOnly />,
        reviews: 274,
        price:  298,
    },
    {
        id: 12,
        image: "./assets/images/jbl-blue.png",
        name: "JBL T450",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "5.0",
        stars: <Rating name="read-only" value={5} readOnly />,
        reviews: 274,
        price:  298,
    },
]

export default productsData;
